
$().ready(function(){$('.undisableOnDomReady').removeAttr('disabled');function showFBRegFlow(){$("#facebook_wrapper").removeClass('hidden');var timeout=3000;for(var i=1;i<=5;i++)
setTimeout("$('.FB_Loader:visible').hide();",timeout*i);return false;}
function hideFBRegFlow(){$("#facebook_wrapper").addClass('hidden');}
$('.tooltip').each(function(){if($(this).data('qtip')){$(this).qtip("destroy");}
$(this).qtip({style:{name:'green',tip:true},position:{adjust:{screen:true}}});});$('.tooltip_green').each(function(){$(this).qtip({style:{name:'green',tip:true},position:{adjust:{screen:true}}});});$('#sex').change(function(){switch($(this).val()){case'm4w':$('#userSex').val('Male');$('#groupSexSeeking').val('Females');break;case'm4m':$('#userSex').val('Male');$('#groupSexSeeking').val('Males');break;case'w4m':$('#userSex').val('Female');$('#groupSexSeeking').val('Males');break;case'w4w':$('#userSex').val('Female');$('#groupSexSeeking').val('Females');break;}});$(document).keydown(function(e){if(!$(e.target).is('body'))return;if(e.keyCode==38||e.keyCode==37){$('#AreaGroups a.less_female_area_groups').click();;}
else if(e.keyCode==40||e.keyCode==39){$('#AreaGroups a.more_female_area_groups').click();;}
else if((e.keyCode==27||e.keyCode==32)&&$("#howItWorksWrapper #close_overlay:visible").length>0)
{$("#howItWorksWrapper #close_overlay").click();}
else if(e.keyCode==32&&$("#watch_how_it_works").length>0){$("#watch_how_it_works input.play").click();}});$("#close_facebook_wrapper").bind('click',function(){hideFBRegFlow();});if(!isLPClickable()&&!isFBRegFlow()){}else if(!isLPClickable()&&isFBRegFlow()){$('#tklp_hero_wrapper, #referral_tklp_hero_wrapper, .newest_female_groups_link, .newest_male_groups_link').unbind('click');$("#view_area_groups, #facebook_search, #tklp_hero_submit, #referral_tklp_hero_submit, #tklp_hero_wrapper, #referral_tklp_hero_wrapper").bind('click',function(){return showFBRegFlow();});$("#area_groups_heading_link, .newest_female_groups_link, .newest_male_groups_link").live('click',function(){return showFBRegFlow();});}else if(isLPClickable()&&!isFBRegFlow()){$('#tklp_hero_wrapper, #referral_tklp_hero_wrapper, #best_value_contents').bind('click',function(){takeUserToRegFlow();});}else if(isLPClickable()&&isFBRegFlow()){$('#tklp_hero_wrapper, #referral_tklp_hero_wrapper, #best_value_contents').bind('click',function(){return showFBRegFlow();});$('#tklp_hero_wrapper, #referral_tklp_hero_wrapper, .newest_female_groups_link, .newest_male_groups_link').unbind('click');$("#view_area_groups, #facebook_search, #tklp_hero_submit, #referral_tklp_hero_submit, #tklp_hero_wrapper, #referral_tklp_hero_wrapper").bind('click',function(){return showFBRegFlow();});$("#area_groups_heading_link, .newest_female_groups_link, .newest_male_groups_link").live('click',function(){return showFBRegFlow();});}});