
jQuery.fn.isHidden=function(){var isHidden=$(this).is(':hidden');return isHidden;};jQuery.fn.jQueryAnimate=jQuery.fn.animate;jQuery.fn.extend({animate:function(prop,speed,easing,callback){if($(this).hasClass('hidden')){$(this).css('display','none').removeClass('hidden');}
$(this).jQueryAnimate(prop,speed,easing,callback);}});function showNextGroupMatch(id){var nextid=parseInt(id)+1;var nextidstr="#"+nextid;var thisGroupMatch=$(".groupmatching").filter(function(){return!$(this).hasClass('hidden');});var nextGroupMatch=thisGroupMatch.next();if($(nextidstr).length>0){thisGroupMatch.addClass("hidden");nextGroupMatch.removeClass("hidden");addMatchingGameClickHandlers();showJGrowlLoadingIndicator();}else{$('#'+id).fadeOut(function(){$('#loadingindicatorcontainer').fadeIn();});$('#'+id).addClass('hidden');showJGrowlLoadingIndicator();ReloadMatchesGame();}
hideJGrowlLoadingIndicator();}
function isLPClickable(){return($('body').hasClass('Clickable'));}
function isFBRegFlow(){return($('#facebook_search').length>0);}
function takeUserToRegFlow(){var url=getRegFlowUrl();window.location=url;}
function getRegFlowUrl(){var url=$("link[rel='baseurl']").attr('href');if(is_auth()){var landingPage=$.cookie('LandingPage');url=url+landingPage+'/Section/Matches/';}else{url=url+'Register/MS/1/';}
return url;}
function is_auth(retStr){if(retStr==1)
return $("meta[name='is_auth']").attr('content');return($("meta[name='is_auth']").attr('content')=='is_auth');}
function getFlagGroupModalBoxHeight(){var height=235;if(!is_auth())
height=400;return height;}
function getFlagUserModalBoxHeight(){var height=235;if(!is_auth())
height=400;return height;}
function IsImageOk(img){if(!img.complete){return false;}
if(typeof img.naturalWidth!="undefined"&&img.naturalWidth==0){return false;}
return true;}
function flagGroupEvents(loadElement){$(".fg_button").die('click');$(".fg_button").live('click',function(){var smURL=$(".fg_form").attr('action');$("#cboxClose").click();var Reason=$("#Reason").val();showJGrowlLoadingIndicator();loadElement.load(smURL,{'Reason':Reason},function(){hideJGrowlLoadingIndicator();loadElement.removeClass('hidden');addClickHandlers();});return false;});}
function flagUserEvents(loadElement){$(".fu_button").die('click');$(".fu_button").live('click',function(){var smURL=$(".fu_form").attr('action');$("#cboxClose").click();var Reason=$("#Reason").val();showJGrowlLoadingIndicator();loadElement.load(smURL,{'Reason':Reason},function(){hideJGrowlLoadingIndicator();loadElement.removeClass('hidden');addClickHandlers();});return false;});}
function currentPoints(){var strVal=" pts";var tmp=$("#PointContainer").text()+"";var currentPoints=parseInt(tmp.replace(strVal,""));return currentPoints;}
function updatePoints(morePoints){var cPoints=currentPoints();var newPoints=cPoints+morePoints;setPoints(newPoints,1)
return newPoints;}
function setPoints(newPoints,flash){var strVal=" pts";var newString=newPoints+strVal;if(flash==1)
{$("#PointContainer").addClass('flash',500);setTimeout('flashPoints("'+newPoints+'");',500);}
else
{$("#PointContainer,.pointsForUser").text(newString);}}
function flashPoints(newPoints){$("#PointContainer").fadeOut(function(){setPoints(newPoints,0);$("#PointContainer").fadeIn(function(){setTimeout("$('#PointContainer').removeClass('flash',500);",500);});});}
function urlHelper(controller,parameters,std_params){var sep='/';var url=$("link[rel='baseurl']").attr('href')+controller+sep;var arrayParams={};if(typeof parameters=="undefined")
parameters={};if(typeof std_params=="undefined")
std_params={};$.each(parameters,function(attr,val){if(typeof val=="object"){arrayParams[attr]=val;}else{url+=attr+sep+(typeof val!="undefined"?val:"")+sep;}});var i=false;$.each(std_params,function(attr,val){if(!i){sep="?";i=true;}else{sep="&";}
if(typeof val=="object"){arrayParams[attr]=val;}else if(typeof val=="undefined"){url+=sep+attr+"=";}else{url+=sep+attr+"="+(typeof val!="undefined"?val:"");}});var i=false;$.each(arrayParams,function(attr,val){$.each(val,function(key,value){if(!i){url+="?";i=true;}else{url+="&";}
url+=attr+"["+key+"]"+"="+value;});});return url;}
function addToolTipHandlers(){$('.tooltip').each(function(){if(!$(this).data('qtip'))
$(this).qtip({style:{name:'ignighter',tip:true},w:{adjust:{screen:true}}});});}
function addOfferHandlers(){$('div#top_offer a#offer_close_button').click(function(){$("div#top_offer").fadeOut();$.get(urlHelper('AjaxCloseRandOffer'));return false;});}
function jGrowlError(message,life){jGrowlHelper(message,life,'error_icon.png','Rut Roh!','error');}
function jGrowlSuccess(message,life){jGrowlHelper(message,life,'success_check.png','Success!','success');}
function jGrowlHelper(message,life,image,title,theme){var baseURL=$("link[rel='baseurl']").attr('href');if(!life){life=5000;}
$.jGrowl("<div id=\"GrowlPic\"><img src=\""+baseURL+"/Images/misc/jgrowl/"+image+"\"></div><span class=\"GrowlHeader\">"+title+"</span><div class='GrowlBody'>"+message+"</div>",{theme:theme,sticky:false,closer:false,life:life});}
function showMore($base,num){$base.siblings(':hidden:lt('+num+')').slideDown();return $base.siblings(':hidden').length;}
function logEvent(eventName,EI,EI2,callback){if(typeof callback!="function")callback=function(){};$.get(urlHelper('EL',{E:eventName,EI:EI,EI2:EI2}),callback);}
function ConsoleLog(strToLog){if(typeof console=='object')
console.log(strToLog);}
function checkHeight(height){var viewportHeight=$(window).height();if(viewportHeight<height){$(window).data('targetHeight',height);$().notification({content:"Whoops! Your browser isn't big enough to display this page. Please expand the window vertically.",classes:['error','checkHeight'],contentClasses:['container_16'],closeButton:true,closeTimeout:0});$(window).bind('resize.checkHeight',function(){var viewportHeight=$(window).height();if(viewportHeight>=$(this).data('targetHeight')){$('.checkHeight').trigger('close');}});}}
function parseUri(str){var o=parseUri.options,m=o.parser[o.strictMode?"strict":"loose"].exec(str),uri={},i=14;while(i--)uri[o.key[i]]=m[i]||"";uri[o.q.name]={};uri[o.key[12]].replace(o.q.parser,function($0,$1,$2){if($1)uri[o.q.name][$1]=$2;});return uri;};parseUri.options={strictMode:false,key:["source","protocol","authority","userInfo","user","password","host","port","relative","path","directory","file","query","anchor"],q:{name:"queryKey",parser:/(?:^|&)([^&=]*)=?([^&]*)/g},parser:{strict:/^(?:([^:\/?#]+):)?(?:\/\/((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?))?((((?:[^?#\/]*\/)*)([^?#]*))(?:\?([^#]*))?(?:#(.*))?)/,loose:/^(?:(?![^:@]+:[^:@\/]*@)([^:\/?#.]+):)?(?:\/\/)?((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/}};function is_array(mixed_var){var key='';if(!mixed_var){return false;}
if(typeof mixed_var==='object'){if(mixed_var.hasOwnProperty){for(key in mixed_var){if(false===mixed_var.hasOwnProperty(key)){return false;}}}
return true;}
return false;}
function ucfirst(str){str+='';var f=str.charAt(0).toUpperCase();return f+str.substr(1);}
function utf8_encode(argString){var string=(argString+'');var utftext="";var start,end;var stringl=0;start=end=0;stringl=string.length;for(var n=0;n<stringl;n++){var c1=string.charCodeAt(n);var enc=null;if(c1<128){end++;}else if(c1>127&&c1<2048){enc=String.fromCharCode((c1>>6)|192)+String.fromCharCode((c1&63)|128);}else{enc=String.fromCharCode((c1>>12)|224)+String.fromCharCode(((c1>>6)&63)|128)+String.fromCharCode((c1&63)|128);}
if(enc!==null){if(end>start){utftext+=string.substring(start,end);}
utftext+=enc;start=end=n+1;}}
if(end>start){utftext+=string.substring(start,string.length);}
return utftext;}
function md5(str){var xl;var rotateLeft=function(lValue,iShiftBits){return(lValue<<iShiftBits)|(lValue>>>(32-iShiftBits));};var addUnsigned=function(lX,lY){var lX4,lY4,lX8,lY8,lResult;lX8=(lX&0x80000000);lY8=(lY&0x80000000);lX4=(lX&0x40000000);lY4=(lY&0x40000000);lResult=(lX&0x3FFFFFFF)+(lY&0x3FFFFFFF);if(lX4&lY4){return(lResult^0x80000000^lX8^lY8);}
if(lX4|lY4){if(lResult&0x40000000){return(lResult^0xC0000000^lX8^lY8);}else{return(lResult^0x40000000^lX8^lY8);}}else{return(lResult^lX8^lY8);}};var _F=function(x,y,z){return(x&y)|((~x)&z);};var _G=function(x,y,z){return(x&z)|(y&(~z));};var _H=function(x,y,z){return(x^y^z);};var _I=function(x,y,z){return(y^(x|(~z)));};var _FF=function(a,b,c,d,x,s,ac){a=addUnsigned(a,addUnsigned(addUnsigned(_F(b,c,d),x),ac));return addUnsigned(rotateLeft(a,s),b);};var _GG=function(a,b,c,d,x,s,ac){a=addUnsigned(a,addUnsigned(addUnsigned(_G(b,c,d),x),ac));return addUnsigned(rotateLeft(a,s),b);};var _HH=function(a,b,c,d,x,s,ac){a=addUnsigned(a,addUnsigned(addUnsigned(_H(b,c,d),x),ac));return addUnsigned(rotateLeft(a,s),b);};var _II=function(a,b,c,d,x,s,ac){a=addUnsigned(a,addUnsigned(addUnsigned(_I(b,c,d),x),ac));return addUnsigned(rotateLeft(a,s),b);};var convertToWordArray=function(str){var lWordCount;var lMessageLength=str.length;var lNumberOfWords_temp1=lMessageLength+8;var lNumberOfWords_temp2=(lNumberOfWords_temp1-(lNumberOfWords_temp1%64))/64;var lNumberOfWords=(lNumberOfWords_temp2+1)*16;var lWordArray=new Array(lNumberOfWords-1);var lBytePosition=0;var lByteCount=0;while(lByteCount<lMessageLength){lWordCount=(lByteCount-(lByteCount%4))/4;lBytePosition=(lByteCount%4)*8;lWordArray[lWordCount]=(lWordArray[lWordCount]|(str.charCodeAt(lByteCount)<<lBytePosition));lByteCount++;}
lWordCount=(lByteCount-(lByteCount%4))/4;lBytePosition=(lByteCount%4)*8;lWordArray[lWordCount]=lWordArray[lWordCount]|(0x80<<lBytePosition);lWordArray[lNumberOfWords-2]=lMessageLength<<3;lWordArray[lNumberOfWords-1]=lMessageLength>>>29;return lWordArray;};var wordToHex=function(lValue){var wordToHexValue="",wordToHexValue_temp="",lByte,lCount;for(lCount=0;lCount<=3;lCount++){lByte=(lValue>>>(lCount*8))&255;wordToHexValue_temp="0"+lByte.toString(16);wordToHexValue=wordToHexValue+wordToHexValue_temp.substr(wordToHexValue_temp.length-2,2);}
return wordToHexValue;};var x=[],k,AA,BB,CC,DD,a,b,c,d,S11=7,S12=12,S13=17,S14=22,S21=5,S22=9,S23=14,S24=20,S31=4,S32=11,S33=16,S34=23,S41=6,S42=10,S43=15,S44=21;str=this.utf8_encode(str);x=convertToWordArray(str);a=0x67452301;b=0xEFCDAB89;c=0x98BADCFE;d=0x10325476;xl=x.length;for(k=0;k<xl;k+=16){AA=a;BB=b;CC=c;DD=d;a=_FF(a,b,c,d,x[k+0],S11,0xD76AA478);d=_FF(d,a,b,c,x[k+1],S12,0xE8C7B756);c=_FF(c,d,a,b,x[k+2],S13,0x242070DB);b=_FF(b,c,d,a,x[k+3],S14,0xC1BDCEEE);a=_FF(a,b,c,d,x[k+4],S11,0xF57C0FAF);d=_FF(d,a,b,c,x[k+5],S12,0x4787C62A);c=_FF(c,d,a,b,x[k+6],S13,0xA8304613);b=_FF(b,c,d,a,x[k+7],S14,0xFD469501);a=_FF(a,b,c,d,x[k+8],S11,0x698098D8);d=_FF(d,a,b,c,x[k+9],S12,0x8B44F7AF);c=_FF(c,d,a,b,x[k+10],S13,0xFFFF5BB1);b=_FF(b,c,d,a,x[k+11],S14,0x895CD7BE);a=_FF(a,b,c,d,x[k+12],S11,0x6B901122);d=_FF(d,a,b,c,x[k+13],S12,0xFD987193);c=_FF(c,d,a,b,x[k+14],S13,0xA679438E);b=_FF(b,c,d,a,x[k+15],S14,0x49B40821);a=_GG(a,b,c,d,x[k+1],S21,0xF61E2562);d=_GG(d,a,b,c,x[k+6],S22,0xC040B340);c=_GG(c,d,a,b,x[k+11],S23,0x265E5A51);b=_GG(b,c,d,a,x[k+0],S24,0xE9B6C7AA);a=_GG(a,b,c,d,x[k+5],S21,0xD62F105D);d=_GG(d,a,b,c,x[k+10],S22,0x2441453);c=_GG(c,d,a,b,x[k+15],S23,0xD8A1E681);b=_GG(b,c,d,a,x[k+4],S24,0xE7D3FBC8);a=_GG(a,b,c,d,x[k+9],S21,0x21E1CDE6);d=_GG(d,a,b,c,x[k+14],S22,0xC33707D6);c=_GG(c,d,a,b,x[k+3],S23,0xF4D50D87);b=_GG(b,c,d,a,x[k+8],S24,0x455A14ED);a=_GG(a,b,c,d,x[k+13],S21,0xA9E3E905);d=_GG(d,a,b,c,x[k+2],S22,0xFCEFA3F8);c=_GG(c,d,a,b,x[k+7],S23,0x676F02D9);b=_GG(b,c,d,a,x[k+12],S24,0x8D2A4C8A);a=_HH(a,b,c,d,x[k+5],S31,0xFFFA3942);d=_HH(d,a,b,c,x[k+8],S32,0x8771F681);c=_HH(c,d,a,b,x[k+11],S33,0x6D9D6122);b=_HH(b,c,d,a,x[k+14],S34,0xFDE5380C);a=_HH(a,b,c,d,x[k+1],S31,0xA4BEEA44);d=_HH(d,a,b,c,x[k+4],S32,0x4BDECFA9);c=_HH(c,d,a,b,x[k+7],S33,0xF6BB4B60);b=_HH(b,c,d,a,x[k+10],S34,0xBEBFBC70);a=_HH(a,b,c,d,x[k+13],S31,0x289B7EC6);d=_HH(d,a,b,c,x[k+0],S32,0xEAA127FA);c=_HH(c,d,a,b,x[k+3],S33,0xD4EF3085);b=_HH(b,c,d,a,x[k+6],S34,0x4881D05);a=_HH(a,b,c,d,x[k+9],S31,0xD9D4D039);d=_HH(d,a,b,c,x[k+12],S32,0xE6DB99E5);c=_HH(c,d,a,b,x[k+15],S33,0x1FA27CF8);b=_HH(b,c,d,a,x[k+2],S34,0xC4AC5665);a=_II(a,b,c,d,x[k+0],S41,0xF4292244);d=_II(d,a,b,c,x[k+7],S42,0x432AFF97);c=_II(c,d,a,b,x[k+14],S43,0xAB9423A7);b=_II(b,c,d,a,x[k+5],S44,0xFC93A039);a=_II(a,b,c,d,x[k+12],S41,0x655B59C3);d=_II(d,a,b,c,x[k+3],S42,0x8F0CCC92);c=_II(c,d,a,b,x[k+10],S43,0xFFEFF47D);b=_II(b,c,d,a,x[k+1],S44,0x85845DD1);a=_II(a,b,c,d,x[k+8],S41,0x6FA87E4F);d=_II(d,a,b,c,x[k+15],S42,0xFE2CE6E0);c=_II(c,d,a,b,x[k+6],S43,0xA3014314);b=_II(b,c,d,a,x[k+13],S44,0x4E0811A1);a=_II(a,b,c,d,x[k+4],S41,0xF7537E82);d=_II(d,a,b,c,x[k+11],S42,0xBD3AF235);c=_II(c,d,a,b,x[k+2],S43,0x2AD7D2BB);b=_II(b,c,d,a,x[k+9],S44,0xEB86D391);a=addUnsigned(a,AA);b=addUnsigned(b,BB);c=addUnsigned(c,CC);d=addUnsigned(d,DD);}
var temp=wordToHex(a)+wordToHex(b)+wordToHex(c)+wordToHex(d);return temp.toLowerCase();}
function base_convert(number,frombase,tobase){return parseInt(number+'',frombase|0).toString(tobase|0);}
var Ignighter1={Main:{getHash:function(href){return href.substring(href.indexOf("#"));},init:function(){addToolTipHandlers();addOfferHandlers();Ignighter1.Main.removeDefaultFormElements();Ignighter1.Main.addEventHandlers();window.baseURL=$("link[rel='baseurl']").attr('href');},requireCookies:function(){$.cookie('cookies_enabled',true);if(!$.cookie('cookies_enabled')){var noCookieURL=urlHelper('NoCookies');if(location.href.indexOf(noCookieURL)==-1){var $noCookieLink=$('<a/>',{href:noCookieURL,target:'_blank',text:'enabling cookies'});$('body').notification({content:'Cookies are disabled in your browser. Follow our guide on '+$noCookieLink.outerHTML()+'.',classes:['info'],contentClasses:['container_16'],closeButton:true,closeTimeout:0});}}
$.cookie('cookies_enabled',null);},show_hide:function(toShow,toHide){$(toShow).css("display","block");$(toHide).css("display","none");},showModalBox:function(relName,_options){$("a[rel='"+relName+"']").each(function(){if(!(function(o){return(o&&"object"==typeof o);})(_options)){_options={};}
options=$.extend({opacity:0.5,speed:350,scrolling:false},_options);$(this).unbind();$(this).colorbox(options);});return false;},clearField:function(e,field){if(e.type=='focus'){if(field.attr('defaultValue')==field.attr('value')){field.attr('value','').addClass('userText');}}else{if(field.attr('value')==''){field.attr('value',field.attr('defaultValue')).removeClass('userText');}}},populateFields:function(fields){for(var i in fields){if(is_array(fields[i]['value'])){for(var j in fields[i]['value']){fields[i]['value'][j]=(fields[i]['value'][j]+'').replace(/\\/g,'');Ignighter1.Main.populateFieldsHelper(fields[i]['name']+'['+j+']',fields[i]['value'][j])}}else{fields[i]['value']=(fields[i]['value']+'').replace(/\\/g,'');Ignighter1.Main.populateFieldsHelper(fields[i]['name'],fields[i]['value']);}}},populateFieldsHelper:function(fieldName,fieldValue){var field=$('[name="'+fieldName+'"]');if(fieldValue!=''&&fieldValue!=null){field.attr('value',fieldValue);if(field.attr('defaultValue')!=field.attr('value')){field.addClass('userText');}}},removeDefaultFormElements:function(){$('form').bindLast('submit.removeDefaultFormElements',function(){return Ignighter1.Main.removeDefaultFormElementsHelper(this);});},removeDefaultFormElementsHelper:function(form){$(form).find(':input').filter(function(){return(($(this).is(':text')||$(this).is('textarea'))&&$(this).attr('value')==$(this).attr('defaultValue')&&!$(this).hasClass('noclearField')&&!$(this).hasClass('autoValues'));}).attr('name','');return true;},addEventHandlers:function(){$('.undisableOnDomReady').removeAttr('disabled');$('#change_group').unbind('change.Ignighter1').bind('change.Ignighter1',function(){location.href=$('#change_group').find('option:selected').attr('value');});$('#login_tab, #login_close').unbind('click.Ignighter1').bind('click.Ignighter1',function(){$('#login').slideToggle();return false;});$(".gallery_item img").hover(function(){$(this).fadeTo(100,1);},function(){$(this).fadeTo(100,0.5);});$('input:text, textarea').not('.noclearField, .autoValue').clearField();$('.getNotification').unbind('click.getNotification').bind('click.getNotification',function(){var $link=$(this);var url=$link.attr('href');$.getJSON(url,function(data){$().notification({content:data.result.message,classes:[data.result.status],contentClasses:['container_16'],closeButton:true,closeTimeout:1000});if($link.hasClass('removeResult')){$link.closest('.result').slideUp();}});return false;});}}}
$(document).ready(function(){Ignighter1.Main.init();Ignighter1.Main.requireCookies();if($("#dcomm")!=null&&$("#dcomm").length>0)
$("#dcomm").children().each(function(){ConsoleLog($(this).attr("name")+" => "+$(this).attr("value"));});$(document).bind('ajaxSend',function(e,xhr,o){currentHost=parseUri(location.href).host;requestHost=parseUri(o.url).host;if(currentHost!==requestHost&&requestHost.indexOf("ignighter.")!==-1){xhr.open(o.type,o.url.replace(requestHost,currentHost),o.async);}});function attachGiftClick($this,e){$('#attach_gift_container.hidden, #gifts_container.hidden').hide().removeClass('hidden');$('#gifts input:checked').removeAttr('checked').closest('.giftwrapper').removeClass('selected');$('#attach_gift_container').slideToggle(function(){$('#colorbox').colorbox.resize();});$('#gifts_container').slideToggle(function(){$('#colorbox').colorbox.resize();});e.preventDefault();}
function sendMessageFormSubmit($this,e){var smURL=$this.attr('action');var $loadElement=$("#actions_temp");$("#colorbox").colorbox.close();showJGrowlLoadingIndicator();$loadElement.load(smURL,{ReplyToMessageID:$("#ReplyToMessageID").val(),GroupID:$("#GroupID").val(),ResultID:$("#ResultID").val(),ToUserID:$("#ToUserID").val(),SenderID:$("#senderGroup").val(),Subject:$("#subject").val(),Message:$("#message").val(),GiftID:$('#gifts .giftwrapper.selected>input.giftselected').val(),Send:true},function(){hideJGrowlLoadingIndicator();$loadElement.removeClass('hidden');addClickHandlers();});e.preventDefault();};function giftWrapperClick($this,e){$("div.giftwrapper.selected").removeClass('selected');$this.addClass('selected');$this.find('input.giftselected').attr('checked','checked');e.preventDefault();}
function groupieClick($this,e){var url=($this.hasClass('become_groupie')?$this.attr('href'):$this.attr('alt_href'));$this.toggleClass('become_groupie un_groupie');showJGrowlLoadingIndicator();$.get(url,function(response){if(response.indexOf("success")===-1)
$this.toggleClass('become_groupie un_groupie');hideJGrowlLoadingIndicator();$(response).appendTo('body');});e.preventDefault();}
$('#attach_gift, #cancel_attach_gift').live('click.attach_gift',function(e){return attachGiftClick($(this),e);});$("#send_message").live('submit.send_message',function(e){return sendMessageFormSubmit($(this),e);});$("#send_gift").live('submit.send_gift',function(e){return sendMessageFormSubmit($(this),e);});$("div.giftwrapper").live('click.gift_select',function(e){return giftWrapperClick($(this),e);});$('a.groupie_link').live('click.groupie',function(e){return groupieClick($(this),e);});Ignighter1.Main.showModalBox('send_message');});$(window).load(function(){$('img').each(function(){if(!IsImageOk($(this)[0])){var oldUrl=$(this).attr('src');var newUrl=oldUrl;for(i=0;i<10;i++)
{newUrl=newUrl.replace('cdn'+i+'.','cdn.');}
newUrl=newUrl.replace('devcdn.','dev.');newUrl=newUrl.replace('cdn.','www.');$(this).attr('src',newUrl);$(this).load();}
else
{}})});$(window).unbind('facebook.liked').bind('facebook.liked',function(e,href,widget){var object=(/Group/g.test(href)?'Group':'Unkown');var id=base_convert(href.match(/\/ID\/([A-Za-z0-9]+)\//)[1],36,10);logEvent('facebook_like',object,id);});;(function($){$.extend($.fn,{populate:function(values,options){options=$.extend({phpNaming:true,phpIndices:true,useIndices:true},options);if(options.phpIndices){options.phpNaming=true;}
function parseJSON(obj,path){path=path||'';if(obj==undefined){}
else if(obj.constructor==Object){for(var prop in obj){var name=path+(path==''?prop:'['+prop+']');parseJSON(obj[prop],name);}}else if(obj.constructor==Array){for(var i=0;i<obj.length;i++){var index=options.useIndices?i:'';index=options.phpNaming?'['+index+']':index;var name=path+index;parseJSON(obj[i],name);}}else{if(arr[path]==undefined){arr[path]=obj;}
else if(arr[path].constructor!=Array){arr[path]=[arr[path],obj];}
else{arr[path].push(obj);}}}
var arr=new Object();parseJSON(values);flat_json=arr;return $(this).each(function(){$form=$(this);$.each(flat_json,function(name,formValue){if(formValue!=''){formValue=(formValue+'').replace(/\\/g,'');$element=$form.find(':input[name="'+name+'"]');$element.each(function(){var $thisElement=$(this);var type=$thisElement.attr('type').toLowerCase();var tag=$thisElement.attr('tagName').toLowerCase();if(tag=='input'){tag=type;}
switch(tag){case'radio':if($thisElement.val()!=''&&formValue.toString().toLowerCase()==$thisElement.val().toLowerCase()){$thisElement.attr('checked',true);}
break;case'checkbox':if($thisElement.val()!=''&&formValue.toString().toLowerCase()==$thisElement.val().toLowerCase()){$thisElement.attr('checked',true);}
break;case'select':$thisElement.val(formValue).addClass('userText');break;case'text':case'button':case'textarea':case'submit':default:if($thisElement.attr('defaultValue')==$thisElement.val())
$thisElement.val(formValue).addClass('userText');break;}});}});return this;});},autoValues:function(){return $(this).each(function(){$form=$(this);$form.find('input, textarea').filter(function(){if($(this).attr('defaultValue')!=''){return false;}
if(!$(this).attr('title')){return false;}
return true;}).each(function(){titleVal=$(this).attr('title');var currentVal=$(this).val();$(this).attr('defaultValue',titleVal).val((currentVal.length?currentVal:titleVal)).addClass('autoValue').bind('focus.autoValues',function(){if($(this).val()==$(this).attr('defaultValue')){$(this).val('').addClass('userText');}}).bind('blur.autoValues',function(){if($(this).val()==''){$(this).attr('value',$(this).attr('defaultValue')).removeClass('userText');}});});$form.bindLast('submit.autoValues',function(){$(this).find(':input.autoValue').each(function(){if($(this).attr('value')==$(this).attr('defaultValue')){$(this).attr('value','');}});});return this;});}});})(jQuery);;(function($){$.extend($.fn,{bindLast:function(event,cbFunc){return this.each(function(){var highIndex=1000000;var eventData=event.split('.');var eventName=eventData[0];$(this).bind(event,cbFunc);var events=$(this).data('events'),ourIndex=false,usedIndicies={};$.each(events[eventName],function(index,func){if(func===cbFunc){ourIndex=index;}
usedIndicies[index]=1;});if(ourIndex!==false){while(usedIndicies[highIndex]==1){highIndex++;}
events[eventName][highIndex]=events[eventName][ourIndex];delete events[eventName][ourIndex]
$(this).data('events',events);}});}});})(jQuery);;(function($){$.extend($.fn,{seeMore:function(options){options=$.extend({animParams:{'opacity':'show'},animDuration:'normal',animCallback:function(){},seeMoreClass:'see_more',seeLessClass:'see_less',seeMoreBlockClass:'see_more_block',seeMoreTextClass:'see_more_text',seeMoreGroupClass:'see_more_group'},options);return this.each(function(){var rel=$(this).attr('rel');var $container=$(this);var $seeMore;var $seeLess=$('.'+options.seeLessClass+'[rel="'+rel+'"]');if($container.hasClass(options.seeMoreBlockClass)){$('.'+options.seeMoreClass+'[rel="'+rel+'"].'+options.seeMoreGroupClass).remove().children().addClass(options.seeMoreClass).attr('rel',rel).remove().appendTo($container);}
$seeMore=$('.'+options.seeMoreClass+'[rel="'+rel+'"]');$seeLess.die('click.seeMore').live('click.seeMore',function(){var numMore=$seeMore.length;$seeMore.each(function(){$(this).animate(options.animParams,options.animDuration,function(){if($container.hasClass(options.seeMoreTextClass)){hiddenHTML=$(this).remove().html();fullHTML=$.trim($container.html())+$.trim(hiddenHTML);$container.html(fullHTML);}
else if($container.hasClass(options.seeMoreBlockClass)){$(this).removeAttr('rel').removeClass(options.seeMoreClass);}
if(--numMore==0){$container.removeAttr('rel').removeClass(options.seeMoreClass).removeClass(options.seeMoreBlockClass).removeClass(options.seeMoreTextClass);}
options.animCallback();});});$(this).remove();});});}});})(jQuery);;(function($){var class_name='ntfn';var selector='.'+class_name;var container_id=class_name+'_container';$.extend($.fn,{notification:function(options){options=$.extend({content:'&nbsp;',classes:[],contentClasses:[],closeButton:true,closeButtonHTML:"",closeTimeout:0,_forceClose:false},options);var $container=$('#'+container_id);var $notification=$(selector);var topOffset=0;var zIndex=9999999;if(!$container.length)
$container=$('<div/>').attr('id',container_id).appendTo('body');var _notification_remove=function(cbFunc,$ntfn){if(!$.isFunction(cbFunc))
cbFunc=function(){};if($notification.length){$ntfn.remove();$notification=$(selector);}
cbFunc();}
var _notification_close=function(cbFunc,$ntfn){if(!$.isFunction(cbFunc))
cbFunc=function(){};if($notification.length){if(!$ntfn.length)
$ntfn=$(this).closest(selector).filter(':last');$ntfn.slideUp(function(){offset=parseInt($(this).outerHeight());$next=$(this).nextAll(selector);_notification_remove(cbFunc,$ntfn)
if($next.length){if(offset>0){$next.each(function(){$(this).animate({top:"-="+offset+"px"});});}}});}}
_isIE6=function(){return $.browser.msie&&parseInt($.browser.version)==6;}
if(options._forceClose){if($notification.length){$ntfn=$(selector).filter(':first');$ntfn.trigger('close');}
return;}
if($notification.length){$notification.each(function(){topOffset+=$(this).data('outerHeight');zIndex++;});}
var id=class_name+'_'+$notification.length;$notification=$('<div/>').attr('id',id).addClass(class_name).addClass(options.classes.join(' ')).css('top',topOffset+'px').css('z-index',zIndex).hide().data('trusted',true).bind('close',function(){_notification_close(function(){},$(this));}).appendTo($container);$content=$('<div/>').addClass(class_name+'_content'+' '+options.contentClasses.join(' ')).html(options.content).appendTo($notification);$notification.data('outerHeight',$notification.outerHeight());if(options.closeButton){$close=$('<a/>').attr('class',class_name+'_close').html(options.closeButtonHTML).prependTo($notification).click(function(){$(this).closest(selector).filter(':last').trigger('close')});}
if(options.closeTimeout>0)
setTimeout('if($("#'+id+'").length){ $("#'+id+'").trigger("close"); }',options.closeTimeout);if(_isIE6()){$notification.bgiframe();}
if(_isIE6()){$notification.show();}else{var height=$notification.height();$notification.css('minHeight','0px').css('height','0px');$notification.show().animate({height:height},{duration:400});}},_generateNotificationContent:function(options){options=$.extend({introText:'Errors: ',fieldNames:[]},options);var $notification=$(selector);var $content=$('<span>').html(options.introText);var numErrors=options.fieldNames.length;var numPrinted=0;$.each(options.fieldNames,function(index,name){$field=$('form :input[name="'+name+'"]:first');if(!$field.length)
$field=$('form :input[name^="'+name+'["]:first');if($field.length){numPrinted++;text=$field.fancyFormGetNameFromLabel();if(numPrinted==1)
text=ucfirst(text);$link=$('<a>').attr('href','#'+name).text(text).addClass('_scrollToField').appendTo($content);if(numPrinted!=numErrors)
$content.append(", ");}else{numErrors--;}});$(selector+' ._scrollToField').live('click',function(){var url=$(this).attr('href');var fieldName=url.substring(url.indexOf('#')+1);$()._scrollToField({fieldName:fieldName});return false;});return $content.html();},_scrollToField:function(options){options=$.extend({fieldName:[]},options);var $notification=$(selector);var offset=0;$notification.each(function(){offset+=$(this).outerHeight();});$().fancyFormScrollToField({fieldName:options.fieldName,scrollOffset:-1*(offset+10)});}});})(jQuery);;(function($){var BrowserDetect={init:function(){this.browser=this.searchString(this.dataBrowser)||"An unknown browser";this.version=this.searchVersion(navigator.userAgent)||this.searchVersion(navigator.appVersion)||"an unknown version";this.OS=this.searchString(this.dataOS)||"an unknown OS";},searchString:function(data){for(var i=0;i<data.length;i++){var dataString=data[i].string;var dataProp=data[i].prop;this.versionSearchString=data[i].versionSearch||data[i].identity;if(dataString){if(dataString.indexOf(data[i].subString)!=-1)
return data[i].identity;}
else if(dataProp)
return data[i].identity;}},searchVersion:function(dataString){var index=dataString.indexOf(this.versionSearchString);if(index==-1)return;return parseFloat(dataString.substring(index+this.versionSearchString.length+1));},dataBrowser:[{string:navigator.userAgent,subString:"Chrome",identity:"Chrome"},{string:navigator.userAgent,subString:"OmniWeb",versionSearch:"OmniWeb/",identity:"OmniWeb"},{string:navigator.vendor,subString:"Apple",identity:"Safari",versionSearch:"Version"},{prop:window.opera,identity:"Opera"},{string:navigator.vendor,subString:"iCab",identity:"iCab"},{string:navigator.vendor,subString:"KDE",identity:"Konqueror"},{string:navigator.userAgent,subString:"Firefox",identity:"Firefox"},{string:navigator.vendor,subString:"Camino",identity:"Camino"},{string:navigator.userAgent,subString:"Netscape",identity:"Netscape"},{string:navigator.userAgent,subString:"MSIE",identity:"Explorer",versionSearch:"MSIE"},{string:navigator.userAgent,subString:"Gecko",identity:"Mozilla",versionSearch:"rv"},{string:navigator.userAgent,subString:"Mozilla",identity:"Netscape",versionSearch:"Mozilla"}],dataOS:[{string:navigator.platform,subString:"Win",identity:"Windows"},{string:navigator.platform,subString:"Mac",identity:"Mac"},{string:navigator.userAgent,subString:"iPhone",identity:"iPhone/iPod"},{string:navigator.platform,subString:"Linux",identity:"Linux"}]};BrowserDetect.init();window.$.client={os:BrowserDetect.OS,browser:BrowserDetect.browser};})(jQuery);jQuery.cookie=function(name,value,options){if(typeof value!='undefined'){options=options||{};if(value===null){value='';options.expires=-1;}
var expires='';if(options.expires&&(typeof options.expires=='number'||options.expires.toUTCString)){var date;if(typeof options.expires=='number'){date=new Date();date.setTime(date.getTime()+(options.expires*24*60*60*1000));}else{date=options.expires;}
expires='; expires='+date.toUTCString();}
var path=options.path?'; path='+(options.path):'';var domain=options.domain?'; domain='+(options.domain):'';var secure=options.secure?'; secure':'';document.cookie=[name,'=',encodeURIComponent(value),expires,path,domain,secure].join('');}else{var cookieValue=null;if(document.cookie&&document.cookie!=''){var cookies=document.cookie.split(';');for(var i=0;i<cookies.length;i++){var cookie=jQuery.trim(cookies[i]);if(cookie.substring(0,name.length+1)==(name+'=')){cookieValue=decodeURIComponent(cookie.substring(name.length+1));break;}}}
return cookieValue;}};(function($){'$:nomunge';var cache={},doTimeout='doTimeout',aps=Array.prototype.slice;$[doTimeout]=function(){return p_doTimeout.apply(window,[0].concat(aps.call(arguments)));};$.fn[doTimeout]=function(){var args=aps.call(arguments),result=p_doTimeout.apply(this,[doTimeout+args[0]].concat(args));return typeof args[0]==='number'||typeof args[1]==='number'?this:result;};function p_doTimeout(jquery_data_key){var that=this,elem,data={},args=arguments,slice_args=4,id=args[1],delay=args[2],callback=args[3];if(typeof id!=='string'){slice_args--;id=jquery_data_key=0;delay=args[1];callback=args[2];}
if(jquery_data_key){elem=that.eq(0);elem.data(jquery_data_key,data=elem.data(jquery_data_key)||{});}else if(id){data=cache[id]||(cache[id]={});}
data.id&&clearTimeout(data.id);delete data.id;function cleanup(){if(jquery_data_key){elem.removeData(jquery_data_key);}else if(id){delete cache[id];}};function actually_setTimeout(){data.id=setTimeout(function(){data.fn();},delay);};if(callback){data.fn=function(no_polling_loop){callback.apply(that,aps.call(args,slice_args))&&!no_polling_loop?actually_setTimeout():cleanup();};actually_setTimeout();}else if(data.fn){delay===undefined?cleanup():data.fn(delay===false);return true;}else{cleanup();}};})(jQuery);(function($){$.toJSON=function(o)
{if(typeof(JSON)=='object'&&JSON.stringify)
return JSON.stringify(o);var type=typeof(o);if(o===null)
return"null";if(type=="undefined")
return undefined;if(type=="number"||type=="boolean")
return o+"";if(type=="string")
return $.quoteString(o);if(type=='object')
{if(typeof o.toJSON=="function")
return $.toJSON(o.toJSON());if(o.constructor===Date)
{var month=o.getUTCMonth()+1;if(month<10)month='0'+month;var day=o.getUTCDate();if(day<10)day='0'+day;var year=o.getUTCFullYear();var hours=o.getUTCHours();if(hours<10)hours='0'+hours;var minutes=o.getUTCMinutes();if(minutes<10)minutes='0'+minutes;var seconds=o.getUTCSeconds();if(seconds<10)seconds='0'+seconds;var milli=o.getUTCMilliseconds();if(milli<100)milli='0'+milli;if(milli<10)milli='0'+milli;return'"'+year+'-'+month+'-'+day+'T'+
hours+':'+minutes+':'+seconds+'.'+milli+'Z"';}
if(o.constructor===Array)
{var ret=[];for(var i=0;i<o.length;i++)
ret.push($.toJSON(o[i])||"null");return"["+ret.join(",")+"]";}
var pairs=[];for(var k in o){var name;var type=typeof k;if(type=="number")
name='"'+k+'"';else if(type=="string")
name=$.quoteString(k);else
continue;if(typeof o[k]=="function")
continue;var val=$.toJSON(o[k]);pairs.push(name+":"+val);}
return"{"+pairs.join(", ")+"}";}};$.evalJSON=function(src)
{if(typeof(JSON)=='object'&&JSON.parse)
return JSON.parse(src);return eval("("+src+")");};$.secureEvalJSON=function(src)
{if(typeof(JSON)=='object'&&JSON.parse)
return JSON.parse(src);var filtered=src;filtered=filtered.replace(/\\["\\\/bfnrtu]/g,'@');filtered=filtered.replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,']');filtered=filtered.replace(/(?:^|:|,)(?:\s*\[)+/g,'');if(/^[\],:{}\s]*$/.test(filtered))
return eval("("+src+")");else
throw new SyntaxError("Error parsing JSON, source is not valid.");};$.quoteString=function(string)
{if(string.match(_escapeable))
{return'"'+string.replace(_escapeable,function(a)
{var c=_meta[a];if(typeof c==='string')return c;c=a.charCodeAt();return'\\u00'+Math.floor(c/16).toString(16)+(c%16).toString(16);})+'"';}
return'"'+string+'"';};var _escapeable=/["\\\x00-\x1f\x7f-\x9f]/g;var _meta={'\b':'\\b','\t':'\\t','\n':'\\n','\f':'\\f','\r':'\\r','"':'\\"','\\':'\\\\'};})(jQuery);;(function(jQuery){jQuery.cookie=function(key,value,options){if(arguments.length>1&&String(value)!=="[object Object]"){options=jQuery.extend({},options);if(value===null||value===undefined){options.expires=-1;}
if(typeof options.expires==='number'){var days=options.expires,t=options.expires=new Date();t.setDate(t.getDate()+days);}
value=String(value);return(document.cookie=[encodeURIComponent(key),'=',options.raw?value:encodeURIComponent(value),options.expires?'; expires='+options.expires.toUTCString():'',options.path?'; path='+options.path:'',options.domain?'; domain='+options.domain:'',options.secure?'; secure':''].join(''));}
options=value||{};var result,decode=options.raw?function(s){return s;}:decodeURIComponent;return(result=new RegExp('(?:^|; )'+encodeURIComponent(key)+'=([^;]*)').exec(document.cookie))?decode(result[1]):null;}})(jQuery);;(function($){$.loadLanguagePackData=function(){window.LanguagePack=false;var LPUrl=urlHelper('AjaxGetLanguagePackData');var LPData={data:$.toJSON(arguments)};$.post(LPUrl,LPData,function(data){window.LanguagePack=data;},'json');}})(jQuery);;(function($){$.extend($.fn,{label:function(){var labels=Array();this.each(function(){var label=$('label[for="'+$(this).attr('id')+'"]')[0];labels.push(label);});return $().pushStack(labels);}});})(jQuery);;(function($){$.extend($.fn,{clearField:function(){$(this).unbind('focus.clearField').bind('focus.clearField',function(){if($(this).attr('defaultValue')==$(this).attr('value')){$(this).val('').addClass('userText');}});$(this).unbind('blur.clearField').bind('blur.clearField',function(){if($(this).val()==''){$(this).val($(this).attr('defaultValue')).removeClass('userText');}});return $(this);}});})(jQuery);(function($){$.fn.outerHTML=function(){return $(this).clone().wrap('<div></div>').parent().html();}})(jQuery);