
$().ready(function(){addToolTipHandlers();$('.undisableOnDomReady').removeAttr('disabled');var $scrollingDiv=$("#upgrade_info");if($scrollingDiv.length>0){var top_margin=40;var top_offset=$scrollingDiv.offset().top-top_margin;var is_scrolled=false;$(window).scroll(function(){if(top_offset<$(window).scrollTop()){$scrollingDiv.css({"marginTop":($(window).scrollTop()-top_offset+top_margin)+"px"});is_scrolled=true;}else if(is_scrolled){$scrollingDiv.css({"marginTop":(top_margin)+"px"});is_scrolled=false;}});}
$('#sex').change(function(){var i_am=$('#sex :selected').val();if(i_am=='w4m'||i_am=='m4m'){$('#female_area_groups').addClass('hidden');$('#male_area_groups').removeClass('hidden');}else{$('#male_area_groups').addClass('hidden');$('#female_area_groups').removeClass('hidden');}});function maleGroups(){$('#male_area_groups .more_male_area_groups').click(function(){if($(this).hasClass('disabled'))return;var $allvisible=$('.newest_male_groups_link:visible');var $hidden=$allvisible.nextAll('.newest_male_groups_link:hidden').slice(0,6);$allvisible.fadeOut('fast',function(){$hidden.fadeIn('fast');});if($hidden.filter(':last').next('.newest_male_groups_link').length==0)
$(this).addClass('disabled');$('.less_male_area_groups').removeClass('disabled');});$('#male_area_groups .less_male_area_groups').click(function(){if($(this).hasClass('disabled'))return;var $allvisible=$('.newest_male_groups_link:visible');var $hidden=$allvisible.prevAll('.newest_male_groups_link:hidden').slice(0,6);$allvisible.fadeOut('fast',function(){$hidden.fadeIn('fast');});if($hidden.filter(':last').prev('.newest_male_groups_link').length==0)
$(this).addClass('disabled');$('.more_male_area_groups').removeClass('disabled');});}
function femaleGroups(){$('#female_area_groups .more_female_area_groups').click(function(){if($(this).hasClass('disabled'))return;var $allvisible=$('.newest_female_groups_link:visible');var $hidden=$allvisible.nextAll('.newest_female_groups_link:hidden').slice(0,6);$allvisible.fadeOut('fast',function(){$hidden.fadeIn('fast');});if($hidden.filter(':last').next('.newest_female_groups_link').length==0)
$(this).addClass('disabled');$('.less_female_area_groups').removeClass('disabled');});$('#female_area_groups .less_female_area_groups').click(function(){if($(this).hasClass('disabled'))return;var $allvisible=$('.newest_female_groups_link:visible');var $hidden=$allvisible.prevAll('.newest_female_groups_link:hidden').slice(0,6);$allvisible.fadeOut('fast',function(){$hidden.fadeIn('fast');});if($hidden.filter(':last').prev('.newest_female_groups_link').length==0)
$(this).addClass('disabled');$('.more_female_area_groups').removeClass('disabled');});}
$(".stop").click(function(){unloadVideo();});$("#close_overlay").click(function(){$("#howItWorks").fadeOut('fast');$("#close_overlay").fadeOut("fast");unloadVideo();$(".play").fadeIn('fast');});$(".play").click(function(){$("#howItWorks").fadeIn('fast');$("#howItWorks")
$("#close_overlay").fadeIn('fast');loadVideo();$(this).fadeOut('fast');});function loadVideo(){swfobject.embedSWF(($("link[rel='baseurl']").attr('href')+"Images/misc/MSLP/TKLP_intro.swf"),"howItWorksContent","660","411","9.0.0");}
function unloadVideo(){if($("#noFlash").length==0){$("#howItWorksContent").empty();}}
function loadHiddenGroups(){loadMaleHiddenGroups();loadFemaleHiddenGroups();}
function loadMaleHiddenGroups(){var $base_img_link=$('#male_area_groups .photos a:first');var baseurl=$("link[rel='baseurl']").attr('href');if(window.maleHiddenGroups&&$('#male_area_groups').length){$.each(window.maleHiddenGroups,function(index,group){var $img_link=$base_img_link.clone();if(!is_auth()){if(isLPClickable())
URL=URL+'sg/1/gid/'+base_convert(group.ID,10,36);else
URL=URL+$img_link.attr('href',urlHelper('Upgrade',{'UT':window.upgradeType,'CTX':'Group','ID':group.ID,'PID':group.photoID}));}
var URL=urlHelper('Register',{'MS':1,'sg':1,'gid':base_convert(group.ID,10,36)});$img_link.attr('href',URL);$img_link.children('img').attr('src',(group.topPhotoURL?group.topPhotoURL:group.imageURL));$img_link.addClass('hidden');$('#male_area_groups .photos').append($img_link);});}
$('#male_area_groups .more_male_area_groups').removeClass('disabled');}
function loadFemaleHiddenGroups(){var $base_img_link=$('#female_area_groups .photos a:first');var baseurl=$("link[rel='baseurl']").attr('href');if(window.femaleHiddenGroups&&$('#female_area_groups').length){$.each(window.femaleHiddenGroups,function(index,group){var $img_link=$base_img_link.clone();var URL=getRegFlowUrl();if(!is_auth()){if(isLPClickable())
URL=URL+'sg/1/gid/'+base_convert(group.ID,10,36);else
URL=URL+$img_link.attr('href',urlHelper('Upgrade',{'UT':window.upgradeType,'CTX':'Group','ID':group.ID,'PID':group.photoID}));}
$img_link.attr('href',URL);$img_link.children('img').attr('src',(group.topPhotoURL?group.topPhotoURL:group.imageURL));$img_link.addClass('hidden');$('#female_area_groups .photos').append($img_link);});}
$('#female_area_groups .more_female_area_groups').removeClass('disabled');}
function loadGroups(){maleGroups();femaleGroups();}
if($('body').hasClass('TKLP')){$(window).load(loadHiddenGroups);}
$("div#AreaGroups").find('.innermodule').each(function(){var baseurl=$("link[rel='baseurl']").attr('href');var url=baseurl+'?Page=AjaxTKLPAreaGroups&ignoreCML=1';var thecontainer=$(this);$.get(url,function(data){thecontainer.fadeOut(function(){thecontainer.empty();thecontainer.append(data);thecontainer.fadeIn();loadGroups();addToolTipHandlers();});addToolTipHandlers();});});});